name: All Builds (APK, IPA, EXE)

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - master
      - main
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.35.3

jobs:

  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flutter Build APK
      run: |
        flutter pub get
        flutter config --no-analytics
        yes | flutter doctor --android-licenses
        flutter build apk --verbose --no-tree-shake-icons --split-per-abi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/app/outputs/flutter-apk
        if-no-files-found: warn
        overwrite: false
        

  build-ipa:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Build iOS app for testing
      run: |
        flutter pub get
        flutter build ipa --no-codesign --no-tree-shake-icons --verbose

    - name: Upload IPA file
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iOS-build-artifact
        path: build/ios/archive
        if-no-files-found: warn
        overwrite: false
    
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build windows app
        run: |
          flutter pub get
          flutter build windows --release --no-tree-shake-icons --verbose

      - name: Upload windows file
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows-build-artifact
          path: build\windows\x64\runner\Release
          if-no-files-found: warn
          overwrite: false
