name: All Builds (Linux, macOS, Android, IPA, APK, AAB)

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - master
      - main
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.32.5

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Patch for linux build
      run: |
        flutter doctor
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        flutter doctor

    - name: Flutter Build Linux
      run: |
        flutter pub get
        flutter config --no-analytics 
        sudo apt-get -y install libsqlite3-0 libsqlite3-dev
        flutter build linux --verbose --no-tree-shake-icons

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: linux-build-artifact
        path: build/linux
        if-no-files-found: warn
        overwrite: false

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flutter Build macOS
      run: |
        flutter pub get
        flutter config --no-analytics
        flutter build macos --verbose --no-tree-shake-icons

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: macos-build-artifact
        path: build/macos
        if-no-files-found: warn
        overwrite: false

  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flutter Build APK
      run: |
        flutter pub get
        flutter config --no-analytics
        yes | flutter doctor --android-licenses
        flutter build apk --verbose --no-tree-shake-icons

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/app/outputs/flutter-apk
        if-no-files-found: warn
        overwrite: false
        

  build-ipa:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Build iOS app for testing
      run: |
        flutter pub get
        flutter build ipa --no-codesign --no-tree-shake-icons --verbose

    - name: Upload IPA file
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iOS-build-artifact
        path: build/ios/archive
        if-no-files-found: warn
        overwrite: false
    
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build windows app
        run: |
          flutter pub get
          flutter build windows --release --no-tree-shake-icons --verbose

      - name: Upload windows file
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windows-build-artifact
          path: build\windows\x64\runner\Release
          if-no-files-found: warn
          overwrite: false
